/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

// USER END

#include "DIALOG.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         (GUI_ID_USER + 0x00)
#define ID_TEXT_TITLE       (GUI_ID_USER + 0x01)
#define ID_TEXT_NOZ_PANEL   (GUI_ID_USER + 0x02)
#define ID_TEXT_NOZ_LABEL   (GUI_ID_USER + 0x03)
#define ID_TEXT_NOZ_VALUE   (GUI_ID_USER + 0x04)
#define ID_TEXT_BED_PANEL   (GUI_ID_USER + 0x05)
#define ID_TEXT_BED_LABEL   (GUI_ID_USER + 0x06)
#define ID_TEXT_BED_VALUE   (GUI_ID_USER + 0x07)
#define ID_PROGBAR_0        (GUI_ID_USER + 0x08)
#define ID_TEXT_TIME        (GUI_ID_USER + 0x09)
#define ID_TEXT_STATUS      (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Page1", ID_WINDOW_0, 0, 0, 310, 188, 0, 0x0, 0 },
  
  // Status
  { TEXT_CreateIndirect, "Status: Idle", ID_TEXT_STATUS, 120, 5, 180, 24, TEXT_CF_RIGHT, 0x0, 0 },

  // Nozzle Panel (Background)
  { TEXT_CreateIndirect, "", ID_TEXT_NOZ_PANEL, 10, 35, 140, 70, 0, 0x0, 0 },
  // Nozzle Content
  { TEXT_CreateIndirect, "Nozzle Temp", ID_TEXT_NOZ_LABEL, 10, 45, 140, 20, TEXT_CF_HCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "0 C", ID_TEXT_NOZ_VALUE, 10, 70, 140, 30, TEXT_CF_HCENTER, 0x0, 0 },

  // Bed Panel (Background)
  { TEXT_CreateIndirect, "", ID_TEXT_BED_PANEL, 160, 35, 140, 70, 0, 0x0, 0 },
  // Bed Content
  { TEXT_CreateIndirect, "Bed Temp", ID_TEXT_BED_LABEL, 160, 45, 140, 20, TEXT_CF_HCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "N/A C", ID_TEXT_BED_VALUE, 160, 70, 140, 30, TEXT_CF_HCENTER, 0x0, 0 },

  // Progress Bar
  { PROGBAR_CreateIndirect, "Progress", ID_PROGBAR_0, 10, 120, 290, 30, 0, 0x0, 0 },
  
  // Time
  { TEXT_CreateIndirect, "Time Left: --:--", ID_TEXT_TIME, 10, 160, 290, 20, TEXT_CF_HCENTER, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Page1'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_DARKGRAY);

    // Status
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_STATUS);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, GUI_GREEN);

    // Nozzle Panel
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NOZ_PANEL);
    TEXT_SetBkColor(hItem, GUI_BLACK);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NOZ_LABEL);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, GUI_LIGHTGRAY);
    TEXT_SetBkColor(hItem, GUI_TRANSPARENT);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NOZ_VALUE);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, GUI_GREEN);
    TEXT_SetBkColor(hItem, GUI_TRANSPARENT);

    // Bed Panel
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BED_PANEL);
    TEXT_SetBkColor(hItem, GUI_BLACK);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BED_LABEL);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, GUI_LIGHTGRAY);
    TEXT_SetBkColor(hItem, GUI_TRANSPARENT);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BED_VALUE);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetTextColor(hItem, GUI_RED);
    TEXT_SetBkColor(hItem, GUI_TRANSPARENT);

    // Progress Bar
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetFont(hItem, GUI_FONT_16B_1);
    PROGBAR_SetBarColor(hItem, 0, GUI_DARKGRAY);
    PROGBAR_SetBarColor(hItem, 1, GUI_GREEN);

    // Time
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TIME);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, GUI_WHITE);

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePage1
*/
WM_HWIN CreatePage1(WM_HWIN hParent);

WM_HWIN CreatePage1(WM_HWIN hParent) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hParent, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
