/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (GUI_ID_USER + 0x00)
#define ID_TEXT_FIL      (GUI_ID_USER + 0x01)
#define ID_TEXT_WEIGHT   (GUI_ID_USER + 0x02)
#define ID_BTN_START     (GUI_ID_USER + 0x03)
#define ID_BTN_PAUSE     (GUI_ID_USER + 0x04)
#define ID_BTN_STOP      (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Page3", ID_WINDOW_0, 0, 0, 310, 194, 0, 0x0, 0 },
  
  // Filament Info
  { TEXT_CreateIndirect, "Filament Weight:", ID_TEXT_FIL, 10, 10, 150, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0 g", ID_TEXT_WEIGHT, 160, 10, 100, 20, 0, 0x0, 0 },

  // Control Buttons
  { BUTTON_CreateIndirect, "START PRINT", ID_BTN_START, 10, 40, 290, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PAUSE PRINT", ID_BTN_PAUSE, 10, 90, 140, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "STOP PRINT", ID_BTN_STOP, 160, 90, 140, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_BLACK);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FIL);
    TEXT_SetTextColor(hItem, GUI_LIGHTGRAY);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEIGHT);
    TEXT_SetTextColor(hItem, GUI_WHITE);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BTN_START: // Notifications sent by 'START PRINT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BTN_PAUSE: // Notifications sent by 'PAUSE PRINT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BTN_STOP: // Notifications sent by 'STOP PRINT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePage3
*/
WM_HWIN CreatePage3(WM_HWIN hParent);
WM_HWIN CreatePage3(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hParent, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
