/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "usart.h"
#include "esp32.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (GUI_ID_USER + 0x00)
#define ID_BTN_CAM       (GUI_ID_USER + 0x01)
#define ID_TEXT_CAM_ST   (GUI_ID_USER + 0x02)
#define ID_TEXT_SYS_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_SYS_2    (GUI_ID_USER + 0x04)
#define ID_TEXT_SYS_IP   (GUI_ID_USER + 0x05)
#define ID_BTN_ESP32_BURN (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{WINDOW_CreateIndirect, "Page4", ID_WINDOW_0, 0, 0, 310, 194, 0, 0x0, 0},

	// Camera Control
	{BUTTON_CreateIndirect, "Toggle Camera", ID_BTN_CAM, 10, 10, 140, 40, 0, 0x0, 0},
	{TEXT_CreateIndirect, "Camera: OFF", ID_TEXT_CAM_ST, 160, 20, 140, 20, 0, 0x0, 0},

	// System Info
	{TEXT_CreateIndirect, "System Info:", ID_TEXT_SYS_1, 10, 70, 290, 20, 0, 0x0, 0},
	{TEXT_CreateIndirect, "FW: v1.0.0", ID_TEXT_SYS_2, 10, 95, 290, 20, 0, 0x0, 0},
	{TEXT_CreateIndirect, "IP: ---", ID_TEXT_SYS_IP, 10, 120, 290, 20, 0, 0x0, 0},
	{BUTTON_CreateIndirect, "esp32 burn", ID_BTN_ESP32_BURN, 10, 145, 140, 40, 0, 0x0, 0},
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg) {
	int NCode;
	int Id;
	WM_HWIN hItem;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
		case WM_INIT_DIALOG:
			hItem = pMsg->hWin;
			WINDOW_SetBkColor(hItem, GUI_DARKGRAY);

			// Toggle Camera Button
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BTN_CAM);
			BUTTON_SetFont(hItem, GUI_FONT_16B_1);
			BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);
			BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);

			// Camera Status
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CAM_ST);
			TEXT_SetTextColor(hItem, GUI_RED);
			TEXT_SetFont(hItem, GUI_FONT_16B_1);

			// System Info Label
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SYS_1);
			TEXT_SetFont(hItem, GUI_FONT_16B_1);
			TEXT_SetTextColor(hItem, GUI_LIGHTGRAY);

			// System Info Value
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SYS_2);
			TEXT_SetFont(hItem, GUI_FONT_16B_1);
			TEXT_SetTextColor(hItem, GUI_WHITE);

			// System Info IP
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SYS_IP);
			TEXT_SetFont(hItem, GUI_FONT_16B_1);
			TEXT_SetTextColor(hItem, GUI_WHITE);
			if (strlen(ip) > 0) {
				char ipText[20];
				snprintf(ipText, sizeof(ipText), "IP: %s", ip);
				TEXT_SetText(hItem, ipText);
			}

			// ESP32 Burn Button
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BTN_ESP32_BURN);
			BUTTON_SetFont(hItem, GUI_FONT_16B_1);
			break;
		case WM_NOTIFY_PARENT:
			Id = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch (Id) {
				case ID_BTN_CAM: // Notifications sent by 'Toggle Camera'
					switch (NCode) {
						case WM_NOTIFICATION_CLICKED:
							// USER START (Optionally insert code for reacting on notification message)
							// USER END
							break;
						case WM_NOTIFICATION_RELEASED:
							// USER START (Optionally insert code for reacting on notification message)
							// USER END
							break;
							// USER START (Optionally insert additional code for further notification handling)
							// USER END
					}
					break;
				case ID_BTN_ESP32_BURN:
					switch (NCode) {
						case WM_NOTIFICATION_RELEASED:
							{
								static int uart2_disabled = 0;
								if (uart2_disabled == 0) {
									HAL_UART_MspDeInit(&ESP32_USART_PORT);
									uart2_disabled = 1;
									GUI_MessageBox("uart2 disabled", "Info", GUI_MESSAGEBOX_CF_MODAL);
								} else {
									HAL_UART_MspInit(&ESP32_USART_PORT);
									uart2_disabled = 0;
									GUI_MessageBox("uart2 enabled", "Info", GUI_MESSAGEBOX_CF_MODAL);
								}
							}
							break;
					}
					break;
					// USER START (Optionally insert additional code for further Ids)
					// USER END
			}
			break;
		// USER START (Optionally insert additional message handling)
		// USER END
		default:
			WM_DefaultProc(pMsg);
			break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePage4
*/
WM_HWIN CreatePage4(WM_HWIN hParent);

WM_HWIN CreatePage4(WM_HWIN hParent) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hParent, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
